// <auto-generated />
using Icatu.EmployeeManagerAPI.Core.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Icatu.EmployerManagerAPI.Core.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    partial class EmployeeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Icatu.EmployeeManagerAPI.Core.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Department")
                        .HasColumnName("Department")
                        .HasMaxLength(10);

                    b.Property<string>("Email")
                        .HasColumnName("Email")
                        .HasMaxLength(40);

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasMaxLength(60);

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
